version: "3.8"

networks:
  web-networks:
    driver: bridge
    name: web-networks
services:
  nginx:
      image: nginx:alpine
      container_name: nndweb_nginx
      restart: unless-stopped
      tty: true
      environment:
        - NGINX_APP_HOST=${APP_DOMAIN_NAME}
      ports:
        - "19002:8002"
      volumes:
        - ../src:/var/www/app
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ../.docker_configs/certs:/etc/nginx/certs
        - ./php-fpm/php-fpm.log:/var/log/php-fpm.log
        - ./nginx:/var/log/nginx
      depends_on:
        - php
        - mysql
      networks:
        - web-networks
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nndweb_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 104857600
      MEMORY_LIMIT: 2G
      # MAX_EXECUTION_TIME: 600
    ports:
      - "8000:80"
    networks:
      - web-networks
  mysql:
    image: mysql
    container_name: nndweb_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "23009:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    # user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      MYSQL_DATABASE: laravel
      MYSQL_USER: nndweb
      MYSQL_PASSWORD: DLTedTfrVzYbrYv9
    networks:
      - web-networks
      
  php:
    build: .
    container_name: nndweb_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ../src:/var/www/app
      # - ./nginx_log:/var/www/nginx
      # - ./php-fpm/php-fpm.log:/var/log/php-fpm.log
    ports:
      - "9001:9000"
    networks:
      - web-networks
    command: >
      sh -c "chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap/cache &&
            chmod -R 775 /var/www/app/storage /var/www/app/bootstrap/cache &&
         exec docker-php-entrypoint php-fpm"

volumes:
  data_mysql: {}
